kind: Template
apiVersion: v1
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: cpu-tcp-proxy
    data:
      location-root.conf: ${PROXY_LOCATION_ROOT}
parameters:
  - name: PROXY_LOCATION_ROOT
    displayName: Proxy Location / Configuration file
    description: A string, in nginx CONF format, with the location / dynamic configuration
    required: true
